# Generated by Django 3.1.5 on 2021-08-02 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BC_tsmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='coins'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prev_hash',
            field=models.CharField(default='', max_length=150, verbose_name='previous hash'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_user',
            field=models.CharField(default='', max_length=150, verbose_name='send coins to'),
        ),
    ]
