# Generated by Django 3.1.5 on 2021-08-02 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BC_tsmr', '0002_auto_20210802_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user created transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prev_hash',
            field=models.CharField(max_length=150, verbose_name='previous hash'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_user',
            field=models.CharField(max_length=150, verbose_name='send coins to'),
        ),
    ]
